export * from './IMessageData'
export * from './IMeta'
export * from './IDiscordMeta'
export * from './IDiscordConfig'
export * from './IGcpConfig'
export * from './IDiscordMessageRequest'
export * from './IBaseMessage'
export * from './IPerson'
